name: Allan Denot Personal
favicon: null
layout_spectrum: 0.6572266221046448
typography_spectrum: 0.5837742548901588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5080063086934388
  lightness: 0.43004465312696993
  saturation: 0.00843958742916584
  rhythmicContrast: 0.19421224086545408
purpose: []
